name: dadar_i_school
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  get: ^4.6.6 # State Management!
  get_it: ^8.0.2 # locator
  dio: ^5.7.0 # Network handling
  shared_preferences: ^2.3.3 # Local Storage!
  flutter_cache_manager: ^3.4.1

  # Download!
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Localization!
  intl: ^0.20.0
  share_plus: ^12.0.0
  url_launcher: ^6.3.2
  image_picker: ^1.2.0
  flutter_hls_parser: ^2.0.1
  flutter_image_compress: ^2.3.0
  youtube_player_flutter: ^9.1.2

  # UI Helpers!
  shimmer: ^3.0.0
  video_player: ^2.10.0
  carousel_slider: ^5.1.1

  # Font Style!
  google_fonts: ^6.2.1
  html: ^0.15.5

  # Utilities!
  connectivity_plus: ^7.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - lib/l10n/
    - assets/app_src/
    - assets/dummy_img/
    - assets/app_src/icon/
    - assets/app_src/icon/social_ic/
    - assets/json/beginner_spoken_english_response.json
    - assets/json/english_grammar_course_response.json
    - assets/json/hundred_days_basic_english_response.json
    - assets/json/hundred_days_spoken_english_response.json
    - assets/json/spoken_english_practice_response.json

